browser:
  browserName: chrome
  headlessMode: true
  timeout: 10
  polling_every_millis: 500
environment:
  appUrl: http://146.59.32.4/index.php
testData:
  searchInput: HUMMINGBIRD
  currency: $
  expectedNumberOfProducts: 1
  minimumPrice: 9.00
  maximumPrice: 11.00
  positionOfMinimumPrice: 0
  positionOfMaximumPrice: 1
  email: MatRos@sii.pl
  password: java1
  basketPopupGenericQuantity: 3
  basketPopupGenericProductName: THE BEST IS YET POSTER
  shippingPrice: 7.00
  basketCalculationsTestIterations: 5
  minQuantity: 1
  maxQuantity: 5
  paymentStatus: Awaiting check payment
  menCategoryText: T-shirts, sweaters, hoodies and men's accessories. From basics to original creations, for every style.
  stationeryCategoryText: Notebooks, agendas, office accessories and more. Everything you need to combine the pleasant and the useful, either at work or at home.
  artCategoryText: Framed poster and vector images, all you need to give personality to your walls or bring your creative projects to life.